apiVersion: v1
kind: Service
metadata:
  name: loki-service
  labels:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki
spec:
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: gateway
    app.kubernetes.io/instance: loki