version: '3'
networks:
  clickvisual-net:
    driver: bridge
services:
  mysql:
    image: mysql:5.7.37
    platform: linux/amd64
    networks:
      - clickvisual-net
    environment:
      MYSQL_ROOT_PASSWORD: shimo
      MYSQL_ROOT_HOST: '%'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci',
      '--port=13306',
      '--init-file=/data/all-in-one/migration/database.sql',
    ]
    ports:
      - 13306:13306
    volumes:
      - ./scripts/migration:/data/all-in-one/migration
    restart: always
  redis:
    image: redis:5.0.14-alpine
    networks:
      - clickvisual-net
    expose:
      - 6380
    restart: always
    command: [ '--port 6380' ]

  clickvisual:
    image: clickvisual/clickvisual:master
    networks:
      - clickvisual-net
    environment:
      EGO_CONFIG_PATH: /clickvisual/config/docker.toml
      EGO_LOG_WRITER: stderr
    expose:
      - 9201
    ports:
      - "19001:19001"
      - "19006:19006"
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis
    restart: always
    command: [ '/bin/sh', '-c', './bin/clickvisual server' ]