apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "simple-clickhouse"
  namespace: clickhouse
spec:
  configuration:
    clusters:
      - name: "simple"
        layout:
          shardsCount: 2
          replicasCount: 2
    users:
      admin/password: "admin"
      admin/networks/ip:
        - "127.0.0.1"
        - "::/0"
  defaults:
    templates:
      podTemplate: pod-template-resource-limit

  templates:
    podTemplates:
      - name: pod-template-resource-limit
        spec:
          containers:
            - name: clickhouse
              image: clickhouse/clickhouse-server
              volumeMounts:
                - name: clickhouse-data-storage
                  mountPath: /var/lib/clickhouse
              # Container has explicitly specified resource limits
              resources:
                requests:
                  memory: "0.5Gi"
                  cpu: "300m"
                limits:
                  memory: "0.5Gi"
                  cpu: "300m"

    volumeClaimTemplates:
      - name: clickhouse-data-storage
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi