apiVersion: apps/v1
kind: Deployment
metadata:
  name: xk6-tracing
  namespace: alloy
spec:
  minReadySeconds: 10
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xk6-tracing
      name: xk6-tracing
  template:
    metadata:
      labels:
        app: xk6-tracing
        name: xk6-tracing
    spec:
      containers:
        - env:
            - name: ENDPOINT
              value: alloy-collector.alloy:4317 # xk6-tracing will send grpc traces to the grpc protocol, rather than http.
          image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
          imagePullPolicy: IfNotPresent
          name: xk6-tracing