apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clickhouse-keeper
  namespace: clickhouse
  labels:
    release: sit-prome
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: prometheus
  namespaceSelector:
    matchNames:
      - clickhouse
  selector:
    matchLabels:
      app: clickhouse-keeper
