apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-deployment
  labels:
    type: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: 'true'
        instrumentation.opentelemetry.io/otel-go-auto-target-exe: '/main'
      labels:
        type: demo
    spec:
      containers:
        - name: foo
          image: mikehsu0618/foo
          ports:
            - containerPort: 8080