adminUser: admin
adminPassword: admin

defaultDashboardsEnabled: true
defaultDashboardsTimezone: Asia/Taipei


image:
  tag: main

replicas: 3

headlessService: true

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo-gateway.tracing
        isDefault: false
      - name: Loki
        type: loki
        access: proxy
        url: http://loki-gateway.loki
        isDefault: false

grafana.ini:
  feature_toggles:
    correlations: true
    editPanelCSVDragAndDrop: true
    enableDatagridEditing: true
    exploreMixedDatasource: true
    nestedFolders: true
    newTraceViewHeader: true
    publicDashboards: true
    traceToMetrics: true
    featureToggleAdminPage: true
    traceQLStreaming: true
    metricsSummary: true
    alertStateHistoryLokiSecondary: true
    alertStateHistoryLokiPrimary: true
    alertStateHistoryLokiOnly: true
    alertingCentralAlertHistory: true
  users:
    viewers_can_edit: true
  unified_alerting.state_history:
    enabled: true
    backend: "loki"
    loki_remote_url: "http://loki-gateway.loki"
  database:
    url: mysql://admin:admin@mysql.mysql:3306/grafana
  unified_alerting:
    enabled: true
    ha_listen_address: "${POD_IP}:9094"
    ha_advertise_address: "${POD_IP}:9094"
    ha_peers: grafana-headless.grafana:9094
  alerting:
    enabled: false

persistence:
  accessModes:
    - ReadWriteOnce
  enabled: true
  size: 10Gi
  type: pvc

plugins:
  - https://grafana.com/api/plugins/grafana-oncall-app/versions/v1.9.0/download;grafana-oncall-app
