{
 "title": "ClickHouseKeeper Dashboard",
 "tags": [
  "altinity",
  "clickhouse-keeper"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(node_namespace_pod:kube_pod_info:{namespace=\"clickhouse\"},namespace)"
    }
   },
   {
    "name": "pod_name",
    "query": {
     "query": "label_values(ClickHouseAsyncMetrics_KeeperTCPThreads,pod_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperAvgLatency{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "avg {{namespace}}.{{pod}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_KeeperMaxLatency{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "max {{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseMetrics_KeeperAliveConnections{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"} ",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Packets per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseAsyncMetrics_KeeperPacketsSent{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}[1m])",
     "legendFormat": "OUT {{namespace}}.{{pod}}"
    },
    {
     "expr": "irate(ClickHouseAsyncMetrics_KeeperPacketsRecive{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}[1m])",
     "legendFormat": "IN {{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "ZNode count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperZnodeCount{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Watch count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperWatchCount{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Ethermals nodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperEphemeralsCount{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Memory data size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperApproximateDataSize{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Outstanding requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ClickHouseMetrics_KeeperOutstandingRequets{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}[1m])",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  },
  {
   "title": "Open file descriptors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_KeeperOpenFileDescriptorCount{namespace=~\"$namespace\", pod=~\"$pod_name\", container=\"clickhouse\"}",
     "legendFormat": "{{namespace}}.{{pod}}"
    }
   ]
  }
 ]
}