# configmap.yaml
agent:
  configMap:
    create: true
    content: |
      logging {
      	level  = "info"
      	format = "logfmt"
      }
      faro.receiver "default" {      
        output {
        logs   = [loki.write.default.receiver]
        traces = [otelcol.exporter.otlp.traces.input]
        }
      }
      
      loki.write "default" {
        endpoint {
        url = "http://loki-gateway.logging/loki/api/v1/push"
        }
      }
      
      otelcol.exporter.otlp "traces" {
        client {
        endpoint = "http://tempo-gateway.tracing"
        }
      }
