fullnameOverride: 'tempo'

reportingEnabled: false

global_overrides:
  metrics_generator_processors:
    - service-graphs
    - span-metrics

ingester:
  replicas: 3
  autoscaling:
    enabled: false
  resources: {}
  persistence:
    enabled: true
  config:
    replication_factor: 3

metricsGenerator:
  enabled: true
  replicas: 1
  resources: {}
  config:
    storage:
      remote_write:
        - send_exemplars: true
          url: http://prometheus-stack-prometheus.prometheus:9090/api/v1/write

distributor:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}
  config:
    log_received_spans:
      enabled: false
      include_all_attributes: false
      filter_by_status_error: false

compactor:
  replicas: 1
  resources: {}
  config:
    compaction:
      block_retention: 48h

querier:
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}
  config:
    trace_by_id:
      query_timeout: 10s
    search:
      query_timeout: 30s
      external_hedge_requests_at: 8s
      external_hedge_requests_up_to: 2
    max_concurrent_queries: 20

queryFrontend:
  replicas: 1
  config:
    max_retries: 2
    search:
      concurrent_jobs: 1000
      target_bytes_per_job: 104857600
    trace_by_id:
      query_shards: 50
      hedge_requests_at: 2s
      hedge_requests_up_to: 2
  autoscaling:
    enabled: false
  resources: {}

multitenancyEnabled: false

traces:
  jaeger:
    grpc:
      enabled: true
    thriftBinary:
      enabled: true
    thriftCompact:
      enabled: true
    thriftHttp:
      enabled: true
  zipkin:
    enabled: true
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
  opencensus:
    enabled: true
  kafka: {}


storage:
  trace:
    backend: local

memcached:
  enabled: true
  replicas: 1
  resources: {}

memcachedExporter:
  enabled: true
  resources: {}

metaMonitoring:
  serviceMonitor:
    enabled: true

  grafanaAgent:
    enabled: false
    installOperator: false
    logs:
      remote:
        url: ''
    metrics:
      remote:
        url: ''

prometheusRule:
  enabled: true

minio:
  enabled: false

gateway:
  enabled: true
  replicas: 1
  autoscaling:
    enabled: false
  resources: {}