apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: benthos
  labels:
    app.kubernetes.io/name: benthos
spec:
  jobLabel: pod-template-hash
  podMetricsEndpoints:
    - honorLabels: false
      honorTimestamps: true
      path: /metrics
      port: http
  selector:
    matchLabels:
        app.kubernetes.io/name: benthos