{
 "title": "Grafana Fara - Frontend Receiver",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "component_id", "query": { "query": "label_values(component_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Measurements",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_measurements_total{component_id=\"$component_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_logs_total{}[$__range]))"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_exceptions_total{component_id=\"$component_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_exporter_errors_total{component_id=\"$component_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Rate Limited Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_id) (increase(faro_receiver_request_duration_seconds_count{status=\"429\", component_id=\"$component_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (component_id) (increase(faro_receiver_request_duration_seconds_count{component_id=\"$component_id\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Sourcemaps Cached",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(faro_receiver_sourcemap_cache_size{component_id=\"auth-app-production\"})",
     "legendFormat": "sourcemaps cached"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by(component_id) (increase(faro_receiver_request_duration_seconds_count{component_id=\"$component_id\", method=\"POST\"}[5m]))",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (component_id) (increase(faro_receiver_request_duration_seconds_count{status=\"429\",component_id=\"$component_id\"}[5m]))",
     "legendFormat": "rate limited"
    },
    {
     "expr": "sum by(component_id) (increase(faro_receiver_request_duration_seconds_count{status=~\"5.*\",component_id=\"$component_id\"}[5m]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Events ingested",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(increase(faro_receiver_logs_total{component_id=\"$component_id\"}[$__interval]))",
     "legendFormat": "logs"
    },
    {
     "expr": "sum(increase(faro_receiver_exceptions_total{component_id=\"$component_id\"}[$__interval]))",
     "legendFormat": "exceptions"
    },
    {
     "expr": "sum(increase(faro_receiver_measurements_total{component_id=\"$component_id\"}[$__interval]))",
     "legendFormat": "measurements"
    }
   ]
  },
  {
   "title": "Exporter errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(component_id) (increase(faro_receiver_exporter_errors_total{component_id=\"$component_id\"}[5m]))",
     "legendFormat": "exporter errors"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(sum(rate(faro_receiver_request_duration_seconds_sum{component_id=\"$component_id\"}[$__rate_interval]))) / (sum(rate(faro_receiver_request_duration_seconds_count{component_id=\"$component_id\"}[$__rate_interval])))",
     "legendFormat": "avg"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(faro_receiver_request_duration_seconds_bucket{component_id=\"$component_id\"}[$__rate_interval])) by (le)) ",
     "legendFormat": "p95"
    }
   ]
  }
 ]
}