apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ethtool-exporter
  namespace: {{ .Values.namespaceOverride | default "kube-system" }}
  labels:
    app: ethtool-exporter
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: ethtool-exporter