version: '3'

services:
  vector:
    build:
      context: .
      dockerfile: Dockerfile
    image: mikehsu0618/vector-geo:latest
    container_name: vector
    ports:
      - "8686:8686"
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
#      - ./../geo/GeoLite2-City.mmdb:/etc/vector/GeoLite2-City.mmdb:ro