
fullnameOverride: faro-collector

crds:
  create: true

alloy:
  configMap:
    create: true
    content: |
      logging {
      	level  = "info"
      	format = "logfmt"
      }
      
      faro.receiver "default" {   
        server {
          cors_allowed_origins = ["*"]
        }
        output {
          logs   = [loki.process.label.receiver]
          traces = [otelcol.exporter.otlp.traces.input]
        }
      }
      
      loki.process "label" {
        stage.logfmt {
          mapping = { 
            "app" = "app_name",
            "version" = "app_version",
            "enviroment" = "app_environment",
            "kind" = "",
          }
        }  

        stage.labels {
          values = {
            app  = "",         
            version = "",
            enviroment = "",
            kind = "",
          }
        }

        forward_to = [loki.write.default.receiver]
      }
      
      loki.write "default" {
        endpoint {
          url = "http://loki-gateway.logging/loki/api/v1/push"
        }
        external_labels = {}
      }
      
      otelcol.exporter.otlp "traces" {
        client {
          endpoint = "tempo-distributor.tracing:4317"
          tls {
            insecure             = true
            insecure_skip_verify = true
          }
        }
      }

  clustering:
    enabled: true

  stabilityLevel: "generally-available"
  enableReporting: false
  extraPorts:
    - name: "faro"
      port: 12347
      targetPort: 12347
      protocol: "TCP"

controller:
  # Must be one of 'daemonset', 'deployment', or 'statefulset'.
  type: 'statefulset'
  replicas: 1
  # -- Whether to enable automatic deletion of stale PVCs due to a scale down operation, when controller.type is 'statefulset'.
  enableStatefulSetAutoDeletePVC: false

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

serviceMonitor:
  enabled: true
  additionalLabels:
    release: 'prometheus-stack'
