# -- Overrides the chart's name
nameOverride: ""

# -- If both are set, Agent Operator will create and maintain a service for scraping kubelets
# https://grafana.com/docs/agent/latest/operator/getting-started/#monitor-kubelets
kubeletService:
  namespace: default
  serviceName: kubelet