apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ethtool-exporter
  labels:
    app: ethtool-exporter
    release: prometheus-stack
spec:
  endpoints:
    - path: /metrics
      port: http
  selector:
    matchLabels:
      app: ethtool-exporter